name: Deploy Docker image

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    Deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout Code
              uses: actions/checkout@v1
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build and Push Docker Image
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: true
                  tags: |
                      vitalykosh/tutor-online:latest
